"""empty message

Revision ID: b61b8381f54c
Revises: 3079240a137b
Create Date: 2021-05-24 20:19:03.796139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61b8381f54c'
down_revision = '3079240a137b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('controller_0_color', sa.String(length=6), nullable=True))
    op.add_column('season', sa.Column('controller_1_color', sa.String(length=6), nullable=True))
    op.add_column('season', sa.Column('controller_2_color', sa.String(length=6), nullable=True))
    op.add_column('season', sa.Column('controller_3_color', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season', 'controller_3_color')
    op.drop_column('season', 'controller_2_color')
    op.drop_column('season', 'controller_1_color')
    op.drop_column('season', 'controller_0_color')
    # ### end Alembic commands ###
