"""empty message

Revision ID: bc54b3ad22b6
Revises: a23d55785874
Create Date: 2019-03-07 15:32:19.883960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc54b3ad22b6'
down_revision = 'a23d55785874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('demo_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'demo_mode')
    # ### end Alembic commands ###
